Fix styling issues and add footer
WSU-4110/TrophyTracker pull request #47
Opened 2024-02-15 18:36 UTC by SukrutN

Will make page look nicer

2024-02-16 20:27 UTC, ThatZiv requested changes
Can we fix the navbar along with the tailwind config? If you want to apply styles to the new `components` folder, just add its glob path in the `content` array

2024-02-16 20:27 UTC, ThatZiv commented on src/app/page.tsx
> +import Hero from "@/components/Hero";
we now have two folders essentially doing the same thing `comps` and `components`, is this something worth even being upset about for me 😂

2024-02-16 20:27 UTC, ThatZiv commented on src/app/layout.tsx
Checked the prevew out for this: https://trophy-tracker-wsu.vercel.app/ for some reason the navbar was changed again. can we just leave it as is so future iterations of it can remain to not be a burden? 
![image](https://github.com/WSU-4110/TrophyTracker/assets/35277113/228cad4c-e048-4815-92d2-db8aa3825aa2)

2024-02-16 20:28 UTC, ThatZiv commented on src/app/layout.tsx
Also when logged out, logging back in doesn't show up. Again, let's just leave the nav alone

2024-02-16 23:47 UTC, ThatZiv commented
The navbar changes are fixed now. Feel free to merge
![image](https://github.com/WSU-4110/TrophyTracker/assets/35277113/aa8eaddf-773b-4d6a-8098-c12a9ccc9b13)

2024-02-17 01:49 UTC, XLRA commented
Reviewed the changes, looks good to me!

2024-02-17 01:50 UTC, XLRA approved these changes
Reviewed the changes, everything looks good!

2024-02-17 01:56 UTC, ThatZiv commented on src/app/page.tsx
> +import Hero from "@/components/Hero";
We'll just have to migrate this later

2024-02-17 01:56 UTC, merged